### ISSUE TITLE
Task Stage Dashboard Table somes times shows Undefined

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#188]
![image](https://user-images.githubusercontent.com/41560543/82633770-a4219080-9c19-11ea-8084-dbd97ee2bc9c.png)

Table glitching out frequently

_Originally posted by @G-Kumaran in https://github.com/adarshmadrecha/jamku/issues/186#issuecomment-632487023_

**Comment by adarshmadrecha** [comment]
A possible fix was released in `v3.17.0`

**Comment by G-Kumaran** [comment]
![image](https://user-images.githubusercontent.com/41560543/88505538-606e4d00-cff5-11ea-9368-733ac16399ca.png)

Unfortunately issue still persists.

**Comment by yogeshkudikala** [comment]
This was solved in v3.2x.x
Hence closing now
